// apps/solid-client/src/components/ui/label.tsx
import { splitProps, type JSX } from "solid-js";
import { cn } from "~/lib/utils";

export function Label(props: JSX.LabelHTMLAttributes<HTMLLabelElement>) {
	const [local, rest] = splitProps(props, ["class"]);
	return (
		<label
			class={cn(
				"text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
				local.class
			)}
			{...rest}
		/>
	);
}

// apps/react-client/components/ui/label.tsx
import * as React from "react";

import { cn } from "@/lib/utils";

const Label = React.forwardRef<HTMLLabelElement, React.ComponentProps<"label">>(
	({ className, ...props }, ref) => (
		<label
			ref={ref}
			className={cn(
				"text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-70",
				className
			)}
			{...props}
		/>
	)
);
Label.displayName = "Label";

export { Label };
